#include "protocol_mapping.hh"

#include "packet/status/c2s/status_request.hh"
#include "packet/status/c2s/ping_request.hh"
#include "packet/status/s2c/status_response.hh"
#include "packet/status/s2c/ping_response.hh"

#include "packet/login/c2s/cookie_response.hh"
#include "packet/login/c2s/encryption_response.hh"
#include "packet/login/c2s/login_acknowledged.hh"
#include "packet/login/c2s/login_plugin_response.hh"
#include "packet/login/c2s/login_start.hh"
#include "packet/login/s2c/cookie_request.hh"
#include "packet/login/s2c/disconnect.hh"
#include "packet/login/s2c/encryption_request.hh"
#include "packet/login/s2c/login_plugin_request.hh"
#include "packet/login/s2c/login_success.hh"
#include "packet/login/s2c/set_compression.hh"

#include "packet/configuration/c2s/acknowledge_finish_configuration.hh"
#include "packet/configuration/c2s/client_information.hh"
#include "packet/configuration/c2s/cookie_response.hh"
#include "packet/configuration/c2s/keep_alive.hh"
#include "packet/configuration/c2s/known_packs.hh"
#include "packet/configuration/c2s/plugin_message.hh"
#include "packet/configuration/c2s/pong.hh"
#include "packet/configuration/c2s/resource_pack_response.hh"
#include "packet/configuration/s2c/add_resource_pack.hh"
#include "packet/configuration/s2c/cookie_request.hh"
#include "packet/configuration/s2c/custom_report_details.hh"
#include "packet/configuration/s2c/disconnect.hh"
#include "packet/configuration/s2c/feature_flags.hh"
#include "packet/configuration/s2c/finish_configuration.hh"
#include "packet/configuration/s2c/keep_alive.hh"
#include "packet/configuration/s2c/known_packs.hh"
#include "packet/configuration/s2c/ping.hh"
#include "packet/configuration/s2c/plugin_message.hh"
#include "packet/configuration/s2c/registry_data.hh"
#include "packet/configuration/s2c/remove_resource_pack.hh"
#include "packet/configuration/s2c/reset_chat.hh"
#include "packet/configuration/s2c/server_links.hh"
#include "packet/configuration/s2c/store_cookie.hh"
#include "packet/configuration/s2c/transfer.hh"
#include "packet/configuration/s2c/update_tags.hh"

#include "packet/play/c2s/acknowledge_configuration.hh"
#include "packet/play/c2s/acknowledge_message.hh"
#include "packet/play/c2s/change_container_slot_state.hh"
#include "packet/play/c2s/change_difficulty.hh"
#include "packet/play/c2s/change_recipe_book_settings.hh"
#include "packet/play/c2s/chat_command.hh"
#include "packet/play/c2s/chat_message.hh"
#include "packet/play/c2s/chunk_batch_received.hh"
#include "packet/play/c2s/click_container.hh"
#include "packet/play/c2s/click_container_button.hh"
#include "packet/play/c2s/client_information.hh"
#include "packet/play/c2s/client_status.hh"
#include "packet/play/c2s/close_container.hh"
#include "packet/play/c2s/command_suggestions_request.hh"
#include "packet/play/c2s/confirm_teleportation.hh"
#include "packet/play/c2s/cookie_response.hh"
#include "packet/play/c2s/debug_sample_subscription.hh"
#include "packet/play/c2s/edit_book.hh"
#include "packet/play/c2s/interact.hh"
#include "packet/play/c2s/jigsaw_generate.hh"
#include "packet/play/c2s/keep_alive.hh"
#include "packet/play/c2s/lock_difficulty.hh"
#include "packet/play/c2s/move_vehicle.hh"
#include "packet/play/c2s/paddle_boat.hh"
#include "packet/play/c2s/pick_item.hh"
#include "packet/play/c2s/ping_request.hh"
#include "packet/play/c2s/place_recipe.hh"
#include "packet/play/c2s/player_abilities.hh"
#include "packet/play/c2s/player_action.hh"
#include "packet/play/c2s/player_command.hh"
#include "packet/play/c2s/player_input.hh"
#include "packet/play/c2s/player_session.hh"
#include "packet/play/c2s/plugin_message.hh"
#include "packet/play/c2s/pong.hh"
#include "packet/play/c2s/program_command_block.hh"
#include "packet/play/c2s/program_command_block_minecart.hh"
#include "packet/play/c2s/program_jigsaw_block.hh"
#include "packet/play/c2s/program_structure_block.hh"
#include "packet/play/c2s/query_block_entity_tag.hh"
#include "packet/play/c2s/query_entity_tag.hh"
#include "packet/play/c2s/rename_item.hh"
#include "packet/play/c2s/resource_pack_response.hh"
#include "packet/play/c2s/seen_advancements.hh"
#include "packet/play/c2s/select_trade.hh"
#include "packet/play/c2s/set_beacon_effect.hh"
#include "packet/play/c2s/set_creative_mode_slot.hh"
#include "packet/play/c2s/set_held_item.hh"
#include "packet/play/c2s/set_player_on_ground.hh"
#include "packet/play/c2s/set_player_position.hh"
#include "packet/play/c2s/set_player_position_rotation.hh"
#include "packet/play/c2s/set_player_rotation.hh"
#include "packet/play/c2s/set_seen_recipe.hh"
#include "packet/play/c2s/signed_chat_command.hh"
#include "packet/play/c2s/swing_arm.hh"
#include "packet/play/c2s/teleport_to_entity.hh"
#include "packet/play/c2s/update_sign.hh"
#include "packet/play/c2s/use_item.hh"
#include "packet/play/c2s/use_item_on.hh"
#include "packet/play/s2c/acknowledge_block_change.hh"
#include "packet/play/s2c/add_resource_pack.hh"
#include "packet/play/s2c/award_statistics.hh"
#include "packet/play/s2c/block_action.hh"
#include "packet/play/s2c/block_entity_data.hh"
#include "packet/play/s2c/block_update.hh"
#include "packet/play/s2c/boss_bar.hh"
#include "packet/play/s2c/bundle_delimiter.hh"
#include "packet/play/s2c/change_difficulty.hh"
#include "packet/play/s2c/chat_suggestions.hh"
#include "packet/play/s2c/chunk_batch_finished.hh"
#include "packet/play/s2c/chunk_batch_start.hh"
#include "packet/play/s2c/chunk_biomes.hh"
#include "packet/play/s2c/chunk_data_and_update_light.hh"
#include "packet/play/s2c/clear_titles.hh"
#include "packet/play/s2c/close_container.hh"
#include "packet/play/s2c/combat_death.hh"
#include "packet/play/s2c/command_suggestions_response.hh"
#include "packet/play/s2c/commands.hh"
#include "packet/play/s2c/cookie_request.hh"
#include "packet/play/s2c/custom_report_details.hh"
#include "packet/play/s2c/damage_event.hh"
#include "packet/play/s2c/debug_sample.hh"
#include "packet/play/s2c/delete_message.hh"
#include "packet/play/s2c/disconnect.hh"
#include "packet/play/s2c/disguised_chat_message.hh"
#include "packet/play/s2c/display_objective.hh"
#include "packet/play/s2c/end_combat.hh"
#include "packet/play/s2c/enter_combat.hh"
#include "packet/play/s2c/entity_animation.hh"
#include "packet/play/s2c/entity_effect.hh"
#include "packet/play/s2c/entity_event.hh"
#include "packet/play/s2c/entity_sound_effect.hh"
#include "packet/play/s2c/explosion.hh"
#include "packet/play/s2c/game_event.hh"
#include "packet/play/s2c/hurt_animation.hh"
#include "packet/play/s2c/initialize_world_border.hh"
#include "packet/play/s2c/keep_alive.hh"
#include "packet/play/s2c/link_entities.hh"
#include "packet/play/s2c/login.hh"
#include "packet/play/s2c/look_at.hh"
#include "packet/play/s2c/map_data.hh"
#include "packet/play/s2c/merchant_offers.hh"
#include "packet/play/s2c/move_vehicle.hh"
#include "packet/play/s2c/open_book.hh"
#include "packet/play/s2c/open_horse_screen.hh"
#include "packet/play/s2c/open_screen.hh"
#include "packet/play/s2c/open_sign_editor.hh"
#include "packet/play/s2c/particle.hh"
#include "packet/play/s2c/pickup_item.hh"
#include "packet/play/s2c/ping.hh"
#include "packet/play/s2c/ping_response.hh"
#include "packet/play/s2c/place_ghost_recipe.hh"
#include "packet/play/s2c/player_abilities.hh"
#include "packet/play/s2c/player_chat_message.hh"
#include "packet/play/s2c/player_info_remove.hh"
#include "packet/play/s2c/player_info_update.hh"
#include "packet/play/s2c/plugin_message.hh"
#include "packet/play/s2c/projectile_power.hh"
#include "packet/play/s2c/remove_entities.hh"
#include "packet/play/s2c/remove_entity_effect.hh"
#include "packet/play/s2c/remove_resource_pack.hh"
#include "packet/play/s2c/reset_score.hh"
#include "packet/play/s2c/respawn.hh"
#include "packet/play/s2c/select_advancements_tab.hh"
#include "packet/play/s2c/server_data.hh"
#include "packet/play/s2c/server_links.hh"
#include "packet/play/s2c/set_action_bar_text.hh"
#include "packet/play/s2c/set_block_destroy_stage.hh"
#include "packet/play/s2c/set_border_center.hh"
#include "packet/play/s2c/set_border_lerp_size.hh"
#include "packet/play/s2c/set_border_size.hh"
#include "packet/play/s2c/set_border_warning_delay.hh"
#include "packet/play/s2c/set_border_warning_distance.hh"
#include "packet/play/s2c/set_camera.hh"
#include "packet/play/s2c/set_center_chunk.hh"
#include "packet/play/s2c/set_container_content.hh"
#include "packet/play/s2c/set_container_property.hh"
#include "packet/play/s2c/set_container_slot.hh"
#include "packet/play/s2c/set_cooldown.hh"
#include "packet/play/s2c/set_default_spawn_position.hh"
#include "packet/play/s2c/set_entity_metadata.hh"
#include "packet/play/s2c/set_entity_velocity.hh"
#include "packet/play/s2c/set_equipment.hh"
#include "packet/play/s2c/set_experience.hh"
#include "packet/play/s2c/set_head_rotation.hh"
#include "packet/play/s2c/set_health.hh"
#include "packet/play/s2c/set_held_item.hh"
#include "packet/play/s2c/set_passengers.hh"
#include "packet/play/s2c/set_render_distance.hh"
#include "packet/play/s2c/set_simulation_distance.hh"
#include "packet/play/s2c/set_subtitle_text.hh"
#include "packet/play/s2c/set_tab_list_header_and_footer.hh"
#include "packet/play/s2c/set_ticking_state.hh"
#include "packet/play/s2c/set_title_animation_times.hh"
#include "packet/play/s2c/set_title_text.hh"
#include "packet/play/s2c/sound_effect.hh"
#include "packet/play/s2c/spawn_entity.hh"
#include "packet/play/s2c/spawn_experience_orb.hh"
#include "packet/play/s2c/start_configuration.hh"
#include "packet/play/s2c/step_tick.hh"
#include "packet/play/s2c/stop_sound.hh"
#include "packet/play/s2c/store_cookie.hh"
#include "packet/play/s2c/synchronize_player_position.hh"
#include "packet/play/s2c/system_chat_message.hh"
#include "packet/play/s2c/tag_query_response.hh"
#include "packet/play/s2c/teleport_entity.hh"
#include "packet/play/s2c/transfer.hh"
#include "packet/play/s2c/unload_chunk.hh"
#include "packet/play/s2c/update_advancements.hh"
#include "packet/play/s2c/update_attributes.hh"
#include "packet/play/s2c/update_entity_position.hh"
#include "packet/play/s2c/update_entity_position_rotation.hh"
#include "packet/play/s2c/update_entity_rotation.hh"
#include "packet/play/s2c/update_light.hh"
#include "packet/play/s2c/update_objectives.hh"
#include "packet/play/s2c/update_recipe_book.hh"
#include "packet/play/s2c/update_recipes.hh"
#include "packet/play/s2c/update_score.hh"
#include "packet/play/s2c/update_section_blocks.hh"
#include "packet/play/s2c/update_tags.hh"
#include "packet/play/s2c/update_teams.hh"
#include "packet/play/s2c/update_time.hh"
#include "packet/play/s2c/world_event.hh"
#include "packet/status/c2s/ping_request.hh"
#include "packet/status/c2s/status_request.hh"
#include "packet/status/s2c/ping_response.hh"
#include "packet/status/s2c/status_response.hh"

#define PACKET_CONSTRUCTOR(packet) [] (const ByteBuf& buf) { return std::make_unique<packet>(buf); }

#define ADD_PACKET(state, side, packet) {							\
		ByteBuf buf;												\
		packet p(buf);												\
		int id = p.getId(version);									\
		if (id >= 0)												\
			mappings[state][side][id] = PACKET_CONSTRUCTOR(packet);	\
	}

acp::ProtocolMapping::ProtocolMapping(const ProtocolVersion* version)
{
	ADD_PACKET(NetworkState::STATUS, NetworkSide::CLIENT, packet::status::c2s::StatusRequest)
	ADD_PACKET(NetworkState::STATUS, NetworkSide::CLIENT, packet::status::c2s::PingRequest)
	ADD_PACKET(NetworkState::STATUS, NetworkSide::DEST, packet::status::s2c::StatusResponse)
	ADD_PACKET(NetworkState::STATUS, NetworkSide::DEST, packet::status::s2c::PingResponse)

	ADD_PACKET(NetworkState::LOGIN, NetworkSide::CLIENT, packet::login::c2s::LoginStart)
	ADD_PACKET(NetworkState::LOGIN, NetworkSide::CLIENT, packet::login::c2s::EncryptionResponse)
	ADD_PACKET(NetworkState::LOGIN, NetworkSide::CLIENT, packet::login::c2s::LoginPluginResponse)
	ADD_PACKET(NetworkState::LOGIN, NetworkSide::CLIENT, packet::login::c2s::LoginAcknowledged)
	ADD_PACKET(NetworkState::LOGIN, NetworkSide::CLIENT, packet::login::c2s::CookieResponse)
	ADD_PACKET(NetworkState::LOGIN, NetworkSide::DEST, packet::login::s2c::Disconnect)
	ADD_PACKET(NetworkState::LOGIN, NetworkSide::DEST, packet::login::s2c::EncryptionRequest)
	ADD_PACKET(NetworkState::LOGIN, NetworkSide::DEST, packet::login::s2c::LoginSuccess)
	ADD_PACKET(NetworkState::LOGIN, NetworkSide::DEST, packet::login::s2c::SetCompression)
	ADD_PACKET(NetworkState::LOGIN, NetworkSide::DEST, packet::login::s2c::LoginPluginRequest)
	ADD_PACKET(NetworkState::LOGIN, NetworkSide::DEST, packet::login::s2c::CookieRequest)
}

std::unique_ptr<acp::packet::IPacket> acp::ProtocolMapping::create(NetworkState state, NetworkSide sourceSide, int id, const ByteBuf& buf) const
{
	if (!mappings.contains(state))
		return nullptr;
	const auto& stateMappings = mappings.at(state);

	if (!stateMappings.contains(sourceSide))
		return nullptr;
	const auto& sideMappings = stateMappings.at(sourceSide);

	if (!sideMappings.contains(id))
		return nullptr;
	return sideMappings.at(id)(buf);
}
